---
output: github_document
always_allow_html: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  cache = TRUE,
  asciicast_at = "end",
  asciicast_theme = if (Sys.getenv("IN_PKGDOWN") == "true") "pkgdown" else "readme"
)
asciicast::init_knitr_engine(
  startup = quote({
    library(cli)
    library(vlightr)
    options(cli.num_colors = cli::truecolor)
    set.seed(1)
  }),
  echo = TRUE,
  echo_input = FALSE
)
```

# vlightr

<!-- badges: start -->

<!-- badges: end -->

vlightr is a package for

## Installation

You can install the development version of vlightr from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("EthanSansom/vlightr")
```

## Features

```{r}
library(vlightr)
```

```{asciicast red-nas}
x <- c(1L, 0L, NA, 1L, 1L, 0L, 1L)
x_hl <- vlightr::highlight(x, is.na, color("red"))
print(x)
print(x_hl)
```

You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. Hey!
